[versions]
glanceAppwidget = "1.1.1"
koinAndroidxCompose = "4.1.1"
koinAndroidxWorkmanager = "4.1.1"
ksp = "2.2.20-2.0.2"
androidxWorkRuntimeKtx = "2.10.5"
accompanistSwiperefresh = "0.36.0"
androidxActivityComposeVersion = "1.11.0"
androidxCoreKtx = "1.17.0"
androidxEspressoCore = "3.7.0"
androidxJunitVersion = "1.3.0"
androidxLifecycleRuntimeKtxVersion = "2.9.4"
browser = "1.9.0"
datastorePreferences = "1.1.7"
jsoup = "1.21.2"
junit = "4.13.2"
lifecycleViewmodelCompose = "2.9.4"
okhttp = "5.2.1"
timber = "5.0.1"
material3 = "1.4.0"
foundationLayout = "1.9.3"
androidApplication = "8.13.0"
kotlinAndroid = "2.2.20"
composePlugin = "2.2.20"
paletteKtx = "1.0.0"
uiGraphics = "1.9.4"

[libraries]
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glanceAppwidget" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkRuntimeKtx" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-activity-compose-v1110 = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityComposeVersion" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-ui-tooling-preview3 = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui-tooling3 = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui3 = { module = "androidx.compose.ui:ui" }
androidx-core-ktx-v1170 = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core-v370 = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCore" }
androidx-junit-v130 = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
androidx-lifecycle-runtime-ktx-v294 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeKtxVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinAndroidxWorkmanager" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-material3-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "androidApplication" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composePlugin" }
